### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Ripcord227** [PushpenderIndia/crypter#12]
This is the error it gives me. I am on Python 3.10.4 

C:\Users\maxin\OneDrive\Desktop\crypter-master>python3 Cryptor
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by arjonkman** [comment]
"Python was not found"
run it with "py" instead of "python3"

**Comment by Ripcord227** [comment]
> 

[*] Making Backup ...
Traceback (most recent call last):
  File "C:\Users\maxin\OneDrive\Desktop\crypter-master\crypter.py", line 23, in <module>
    shutil.copyfile(path, path + ".bak")
  File "C:\Users\maxin\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\maxin\\OneDrive\\Desktop\\live-and-let-die'

this is what it tells me when i try
